name = "fenvelopes"
version = "0.1.0"
license = "license"
author = "Federico E. Benelli"
maintainer = "federico.benelli@mi.unc.edu.ar"
copyright = "Copyright 2023, Federico E. Benelli"

[build]
link = ["blas"]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
stdlib = "*"
# minpack= "*"
ftools = { git = "https://github.com/fedebenelli/ftools" }
yaeos  = { git = "https://github.com/fedebenelli/yaeos"  }
FLAP   = { git = "https://github.com/szaghi/FLAP", tag="v1.2.5" }
fordiff = {git="https://github.com/gha3mi/fordiff.git"}
forsolver = { git="https://github.com/gha3mi/forsolver.git" }
progress-bar = { git="https://github.com/zoziha/progress-bar" }

[fortran]
implicit-external = false # default: false
implicit-typing   = false # default: false

[preprocess]
[preprocess.cpp]
[preprocess.fypp]